# Generated by Django 3.2.13 on 2022-11-22 13:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20221122_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watched_users',
            field=models.ManyToManyField(related_name='watched_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
