# Generated by Django 3.2.13 on 2022-11-23 10:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='/profile/default.png', upload_to=accounts.models.profile_image_path),
        ),
    ]
