# Generated by Django 3.2.13 on 2022-11-23 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_auto_20221123_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='origin_comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.post'),
        ),
    ]
